package com.live;// Generated by Selenium IDE
import com.testng.TestStatic;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class LivePublishTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  WebDriverWait wait;


  /**
   * 二维数组，准备测试的参数
   * @return
   */
  @DataProvider(name = "liveDataProvider")
  public Object[][] rangeData() {
    String liveTitle = "自嘲";
    String liveUrl = "www.baidu.com";
    String startTime = "2021-01-20 09:00:00";
    String liveDuration = "//option[. = '7小时']";
    String liveDescription = "运交华盖欲何求？未敢翻身已碰头。\\n破帽遮颜过闹市，漏船载酒泛中流。\\n横眉冷对千夫指，俯首甘为孺子牛。\\n躲进小楼成一统，管";
    return new Object[][]{
            {liveTitle, liveUrl, liveDuration,liveDescription}
    };
  }

  /**
   * 测试前获取浏览器driver
   */
  @BeforeClass
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", TestStatic.FIREFOXDRIVERVALUE);
    System.out.println("启动 ...");
    ChromeOptions chromeOptions = new ChromeOptions();
    //启动一个 chrome 实例
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    //显式等待， 针对某个元素等待
    wait = new WebDriverWait(driver, 10, 1);
  }

  @Test(dataProvider = "liveDataProvider", priority = 0)
  public void livePublishTest() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.cssSelector(".yun-solution-list-item:nth-child(8) > .img-wrap")).click();
    driver.findElement(By.cssSelector(".yun-solution-list-item:nth-child(6) > .img-wrap")).click();
    driver.findElement(By.linkText("管理端")).click();
    driver.findElement(By.linkText("直播管理")).click();
    driver.findElement(By.id("liveTitle")).click();
    driver.findElement(By.id("liveTitle")).sendKeys("自嘲");
    driver.findElement(By.id("liveUrl")).click();
    driver.findElement(By.id("liveUrl")).sendKeys("www.baidu.com");
    driver.findElement(By.id("startTime")).click();
    driver.findElement(By.id("startTime")).sendKeys("2021-01-20 09:00:00");
   // driver.findElement(By.cssSelector(".laydate-btns-now")).click();
    driver.findElement(By.id("liveDuration")).click();
    {
      WebElement dropdown = driver.findElement(By.id("liveDuration"));
      dropdown.findElement(By.xpath("//option[. = '7小时']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(7)")).click();
    driver.findElement(By.id("liveDescription")).click();
    driver.findElement(By.id("liveDescription")).sendKeys("运交华盖欲何求？未敢翻身已碰头。\\n破帽遮颜过闹市，漏船载酒泛中流。\\n横眉冷对千夫指，俯首甘为孺子牛。\\n躲进小楼成一统，管");
    driver.findElement(By.id("upImageBtn")).click();
    driver.findElement(By.id("publishSup")).click();
    driver.findElement(By.cssSelector(".layui-this:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".layui-this:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("直播")).click();
  }

  @After
  public void tearDown() {
    driver.quit();
  }
}
