server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: image/jpeg,image/png,image/gif,application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 300MB
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.244.66:8443/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Yanglao123
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最大，最小
    initial-size: 1
    max-active: 20
    min-idle: 1
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true


  jackson: # 格式化时间
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



