package com.project;// Generated by Selenium IDE
import com.testng.BaseTest;
import com.testng.TestStatic;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.testng.annotations.Test;

public class ProjectApplyTest extends BaseTest {

  @Test
  public void projectApply() throws InterruptedException {
    driver.get(TestStatic.INDEXURL);
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".current > .img-wrap")).click();
    Thread.sleep(2000);
    /**
     * 设置标题
     */
    wait.until(new ExpectedCondition<WebElement>() {
      @Override
      public WebElement apply(WebDriver text) {
        return text.findElement(By.linkText("个人工作台"));
      }
    }).click();
    Thread.sleep(1000);
    wait.until(new ExpectedCondition<WebElement>() {
      @Override
      public WebElement apply(WebDriver text) {
        return text.findElement(By.linkText("创建项目"));
      }
    }).click();
    Thread.sleep(1000);
    driver.switchTo().frame(0);
    /**
     * 设置标题
     */
    wait.until(new ExpectedCondition<WebElement>() {
      @Override
      public WebElement apply(WebDriver text) {
        return text.findElement(By.id("projectName"));
      }
    }).sendKeys("未来合伙人");
    Thread.sleep(1000);

    driver.findElement(By.id("projectType")).click();
    {
      WebElement dropdown = driver.findElement(By.id("projectType"));
      dropdown.findElement(By.xpath("//option[. = '科创']")).click();
    }
    Thread.sleep(1000);
    driver.findElement(By.cssSelector("#projectType > option:nth-child(4)")).click();
    driver.findElement(By.id("starttime")).click();

    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(4)")).click();

    Thread.sleep(1000);
    driver.findElement(By.id("mainPeople")).click();
    driver.findElement(By.id("mainPeople")).sendKeys("陈兴宇");
    Thread.sleep(1000);

    driver.findElement(By.id("projectSupervisor")).click();
    {
      WebElement dropdown = driver.findElement(By.id("projectSupervisor"));
      dropdown.findElement(By.xpath("//option[. = '里式明']")).click();
    }

    Thread.sleep(1000);
    driver.findElement(By.id("projectPeople")).sendKeys("陈楠洲，陈杏妍");
    Thread.sleep(1000);
    driver.findElement(By.cssSelector("#projectSupervisor > option:nth-child(4)")).click();
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("北京中教天地信息技术有限公司提供项目大纲体系以及培训考试平台和相关考试资料,各地负责招生培训考试工作。国际信息化培训项目是指培训适合我国国情发展的、促进我国信息系统的发展");
    Thread.sleep(2000);
    driver.findElement(By.linkText("申请")).click();
    Thread.sleep(5000);
  }
}
